name: Library is compiling

on:
  push:
    branches:
      - "main"
  pull_request: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

env:
  GRADLE_OPTS: "-Dorg.gradle.jvmargs=-Xmx6g -Dorg.gradle.daemon=false -Dkotlin.incremental=false"

jobs:
  assemble-library:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3.11.0
        with:
          java-version: '17'
          distribution: 'temurin'
      - uses: gradle/gradle-build-action@v2.6.0
        # Don't spend more than 5m rehydrating the cache. Otherwise just move on.
        timeout-minutes: 5
        continue-on-error: true

      - run: ./gradlew clean assemble
